name = "santrionline-next"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "next-app/.vercel/output/static"

[build]
command = "cd next-app && npm install && npm run cf:build"

[vars]
NEXT_PUBLIC_APP_URL = "https://app.santrionline.com"
APP_ENV = "production"
ADMIN_EMAILS = "admin@santrionline.com"

[[d1_databases]]
binding = "DB"
database_name = "inti-santri"
database_id = "b42e974f-4b45-4edc-92e5-553b7c4cbf3b"
preview_database_id = "b42e974f-4b45-4edc-92e5-553b7c4cbf3b"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "santri-online-files"
preview_bucket_name = "santri-online-files-preview"
