name = "santrionline"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "build/client"

[vars]
APP_ENV = "production"

[[d1_databases]]
binding = "SANTRI_DB"
database_name = "santrionline-app"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "SANTRI_BUCKET"
bucket_name = "santrionline-app-files"
preview_bucket_name = "santrionline-app-files-preview"

[[routes]]
pattern = "app.santrionline.com/*"
custom_domain = true
